### ISSUE TITLE
Corriger les erreur client lors de l'envoi de pièces jointes

### ISSUE THREAD

**Issue by kemenaran** [betagouv/demarches-simplifiees.fr#4432]
**Décrivez le bug**

On a depuis une dizaine de jours des messages réguliers de gens qui disent ne pas pouvoir envoyer une pièce-jointe.

**Reproduction**
Comment reproduire le problème :
1. En tant qu'Usager, aller sur une démarche
2. Ajouter une pièce-jointe
3. Une erreur apparaît

**Remonté par**

- `HS #24499` : IE11; `Error storing '<file.pdf>'. Status: 0`
- `HS #24197` : IE11; `Error storing '<file.pdf>'. Status: 0`
- `HS #24193` : Android/Chrome, erreur exacte inconnue
- `HS #24585` : erreur inconnue
- `HS #22348` : Safari Mobile, erreur inconnue

**Capture d'écran**

`HS #24499`:

![image1](https://user-images.githubusercontent.com/179923/67410037-c38d0800-f5bb-11e9-98b6-fc2d17328553.png)

**Appareil et navigateur utilisé**

Pour l'instant j'ai vu du Chrome et du IE 11.

## Pistes

On sait qu'il y a [plusieurs erreurs](https://github.com/betagouv/demarches-simplifiees.fr/issues/4432#issuecomment-548025487) qui causent ces soucis.

Les actions à mener sont :

- [ ] Envoyer les pièces jointes automatiquement dès l'attachement (#4989)
    _(Pour qu'un upload qui échoue ne fasse pas une erreur pile au moment de déposer le dossier.)_
- [ ] Sauvegarder automatiquement les brouillons (#2859)
    _(Pour qu'une erreur d'upload ne perde pas le contenu du brouillon.)_
- [x] Investiguer la cause des erreurs 422

**Comment by kemenaran** [comment]
J'ai réussi à reproduire l'erreur en capture d'écran dans un IE11 sur BrowserStack (mais je n'ai réussi à reproduite qu'une fois, et je n'ai pas retrouvé ensuite).

Dans la console, Internet Explorer disait :

> /rails/active_storage/direct_uploads:
> XmlHttpRequest network error 0x2ef3, Could not complete the operation due to error 00002ef3

L'[erreur 0x2ef3](https://stackoverflow.com/questions/16312938/ie10-ie11-abort-post-ajax-request-after-clearing-cache-with-error-network-error/16818527#16818527), ça a l'air d'être un "IE refuse de lancer la requête assez générique". Y'a pas de solution évidente : des gens suggèrent un problème de Keepalive, de timeout, de Content-type…

**Comment by kemenaran** [comment]
Maintenant qu'on logue les erreurs, on a des traces dans Sentry, et on affiche au moins un message en français aux gens (même s'ils perdent toujours le contenu de leur brouillon).

## Sentry

https://sentry.io/organizations/demarches-simplifiees/issues/1294365165/events/95e87fbb1a4c48118a1c6f124efbdc4e/?environment=production&project=1429547&query=is%3Aunresolved

Beaucoup d'évènements. Ça a l'air d'être essentiellement un `POST https://www.demarches-simplifiees.fr/rails/active_storage/direct_uploads` qui répond régulièrement un 422.

## Kibana

De fait on voit aussi ces 422 dans Kibana. Y'en a une quarantaine par jour.

http://localhost:9003/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(error,status),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:db96a0d0-cc97-11e8-a0a9-4f854c3a7a7a,key:status,negate:!t,params:(query:200,type:phrase),type:phrase,value:'200'),query:(match:(status:(query:200,type:phrase))))),index:db96a0d0-cc97-11e8-a0a9-4f854c3a7a7a,interval:auto,query:(language:lucene,query:%22%2Frails%2Factive_storage%2Fdirect_uploads%22),sort:!('@timestamp',desc))

Ce sont des exceptions `ActionController::InvalidAuthenticityToken`, qui génèrent une réponse `422`.

## État des lieux

- Ces réponses 422 sont plus nombreuses que ce que je croyais.
- À chaque fois, ça veut dire que l'Usager perd le contenu de son brouillon (qui n'est pas enregistré).
- Mais maintenant, on a au moins de l'instrumentation, et des stats.

**Pistes**

- Faire de l'upload immédiat à l'ajout de la PJ ?
- Faire de l'enregistrement de brouillon au fil de l'eau ?
- Comprendre pourquoi on a ces erreurs `InvalidAuthenticityToken` : formulaire resté ouvert trop longtemps, et le token expire ? Problème de navigateur ?

**Comment by kemenaran** [comment]
État après quelques jours de collecte dans Sentry (https://sentry.io/organizations/demarches-simplifiees/issues/1294365165/?project=1429547&query=is%3Aunresolved) : 

- On a environ 100 erreurs d'upload par jour ;
- Y'a une majorité de navigateurs mobiles (Safari Mobile, Chrome Mobile), mais pas que ;
- On voit passer les cas où c'est du 422, avec des breadcrumbs pour identifier le parcours usager ;
- Mais y'a aussi des erreurs "Status: 0" que je m'explique moins ; faut que je segmente.

**Comment by kemenaran** [comment]
Sentry regroupe toutes les erreurs Javascript d'upload dand une même issue. Mais en vrai ça regroupe des messages d'erreurs différents.

Voici une petite analyse des différents types d'erreurs d'upload rencontrées.

## [Error reading \<file\>](https://sentry.io/organizations/demarches-simplifiees/events/?project=1429547&query=%22error+reading%22&statsPeriod=7d)

**Fréquence :** ~ 373 erreurs / semaine

Se produit lorsque le **FileReader** utilisé par ActiveStorage pour générer un checksum échoue, avant même de lancer des requêtes réseau. Ça veut généralement dire que le fichier n'est pas lisible pour une raison ou une autre. Dans ce cas, ActiveStorage [mange malheureusement la cause exacte de l'erreur](https://github.com/rails/rails/blob/046bd75b0e5f7ec35f5136ccaaec6676dc1b88cc/activestorage/app/javascript/activestorage/file_checksum.js#L38).

**Navigateurs :** Firefox 70, Mobile Safari 12, Chrome Mobile…

## [Error creating Blob for "\<file\>". Status: 422](https://sentry.io/organizations/demarches-simplifiees/events/?project=1429547&query=%22error+creating+blob+for%22+%22Status%3A+422%22&statsPeriod=7d)

**Fréquence :** ~ 133 erreurs / semaine

Se produit lorsque [la requête Ajax envoyée par BlobRecord](https://github.com/rails/rails/blob/75d0a46b6c836dc57b9f78760b1277a242010b52/activestorage/app/javascript/activestorage/blob_record.js) à `/rails/active_storage/direct_upload` échoue avec une erreur 422 (token d'authentification invalide). Généralement on a également la stacktrace côté Ruby.

**Navigateurs :** beaucoup de Chrome Mobile, mais aussi du Firefox 70, Mobile Safari 12, IE…

## [Error creating Blob for "\<file\>". Status: 0](https://sentry.io/organizations/demarches-simplifiees/events/?project=1429547&query=%22error+creating+blob+for%22+%22Status%3A+0%22&statsPeriod=7d)

**Fréquence :** ~ 26 erreurs / semaine

Se produit lorsque [la requête Ajax envoyée par BlobRecord](https://github.com/rails/rails/blob/75d0a46b6c836dc57b9f78760b1277a242010b52/activestorage/app/javascript/activestorage/blob_record.js) à `/rails/active_storage/direct_upload` échoue au niveau du client ou du réseau (requête annulée ou timeoutée). 

Généralement il y a un délai de 8 à 20s entre l'envoi de la requête POST et la réponse `0`.

**Navigateurs :** surtout du desktop sur Windows (mais une occurence sur Safari Mobile).

## TODO

- [ ] Investiguer si les breadcrumbs fournissent une info (du genre "C'est toujours quand le formulaire est ouvert depuis 3h").
- [ ] Investiguer comment on pourrait éviter les erreurs 422. P-ê supprimer le token qq jours et voir si ça change qqc ?

**Comment by kemenaran** [comment]
Maintenant que les erreurs Javascript à l'upload sont correctement groupées par Sentry, j'ai investigué les **erreurs 422 à l'upload**. Y'a deux choses intéressantes :

1. Les erreurs 422 concernent uniquement des navigateurs mobile (Safari Mobile, Chrome Mobile).
2. Dans Sentry, les breadcrumbs indiquent quasiment tout le temps qu'avant l'erreur, l'usager clique sur un lien du footer – mais sans requête GET subséquente, et sans naviguer en dehors de la page.

#### Hypothèse A

Le clic dans le footer ouvre un nouvel onglet, le navigateur décharge la page précédente, quand l'usager revient sur l'onglet précédent le navigateur la recharge depuis le cache, mais sans le cookie de session (ou avec un token CSRF expiré).

_Je n'ai pas réussi à reproduire ce scénario, faute de pouvoir contrôler le dé-chargement de la page dans Safari Mobile._

#### Hypothèse B

Le navigateur se ferme, puis en se rouvrant essaie de charger le HTML depuis le cache, mais sans le cookie de session (ou, pareil, avec un token CSRF expiré).

_J'ai réussi à reproduire ça dans Safari Desktop._

1. Ouvrir la page de connexion (https://www.demarches-simplifiees.fr/users/sign_in)
2. Se connecter SANS COCHER LA CASE "SE SOUVENIR DE MOI"
3. Ouvrir un formulaire
4. Fermer Safari (Cmd+Q)
5. Ré-ouvrir Safari. La page avec le formulaire s'affiche.
6. Soumettre le formulaire.

Boum. Y'a plus de cookie de session, donc le token CSRF de la requête ne matche plus le cookie de session.

**Comment by kemenaran** [comment]
État des lieux sur les erreurs 422 : dire aux navigateurs de ne _jamais_ mettre de HTML en cache a l'air de corriger les erreurs 422 à l'upload.

(En vrai, pour l'Usager, ça ne corrige pas _vraiment_ : ça fait que la page de son formulaire est rechargée automatiquement quand le navigateur redémarre, au passage en perdant les données non enregistrées. Mais c'est un début, au moins l'Usager ne continue pas à remplir un formulaire qu'il ne pourra jamais envoyer).

On est donc bon :

- Sur les erreurs "422 token d'authentification invalide" (corrigé).
- Sur les erreurs "Error uploading file. Status: 0" (on ignore les erreurs de connectivité).

Reste :

- Les nombreuses erreurs "Error reading file. Status: 0".

TODO:

- [ ] Avoir un message d'erreur plus détaillé pour les "Error reading file" (#5051)

**Comment by kemenaran** [comment]
On a maintenant un message d'erreur précis pour les erreurs client qui est remonté dans Sentry.

Les prochaines étapes sont de :

- [ ] Analyser le message d'erreur, en fonction des appareils (Android ou iOS)
- [ ] Voir si on peut arranger la cause du problème
- [ ] Améliorer le message d'erreur affiché
- [ ] Ignorer le reste des problèmes

**Comment by kemenaran** [comment]
On a corrigé ce qu'on pouvait. Reste le retry automatique, traité dans une autre issue.
