### ISSUE TITLE
ETQ Usager, je veux envoyer mes pièces jointes au fur et à mesure

### ISSUE THREAD

**Issue by kemenaran** [betagouv/demarches-simplifiees.fr#4989]
Aujourd'hui on envoie toutes les pièces justificatives d'un dossier d'un coup, quand l'Usager clique sur "Déposer" (ou sur "Enregistrer le brouillon"). C'est en direct-upload, mais malgré tout ça veut dire qu'une erreur d'upload empêche l'enregistrement de tout le dossier.

À la place on devrait envoyer chaque PJ dès qu'elle est attachée au formulaire. Ça permettrait de réduire les erreurs d'upload, en envoyant au fur et à mesure.

## TODO

- [x] Corriger l'upload par des invités (#4981)
- [x] Corriger la création de blocs répétables contenant des PJ (#4993)
- [x] Corriger le clic sur l'icône "Ré-essayer" (#5013)
- [x] Désactiver le "Retry" en cas de 422 de la part de l'upload (#5013)
- [x] Créer des graphes de monitoring sur Kibana
- [x] Activer à 50 % des utilisateurs (rollbacké)
- [x] Résoudre les erreurs 422 à l'attachment (#4432)
- [x] En cas d'erreur "status 0", indiquer "La connexion a été perdue."
- [x] Ré-activer à 50% des utilisateurs
- [x] Activer à 100 % des utilisateurs

**Comment by kemenaran** [comment]
On a également besoin de ça pour enregistrer les brouillons automatiquement (#2859).

**Comment by kemenaran** [comment]
Aujourd'hui c'est en prod, derrière un feature-flag `autoupload_dossier_attachments`.

## TODO

- [x] Corriger l'upload par des invités (#4981)
- [ ] Corriger la création de blocs répétables contenant des PJ

**Comment by kemenaran** [comment]
Pour l'instant ça a l'air de rouler. On a parfois des pics avec beaucoup plus d'erreurs de CSRF qu'avant, mais pour le reste ça ronronne.

Du coup je vais laisser à 50% d'usagers pendant le week-end, et sans doute passer à 100% lundi.

Et je me lance sur "Comprendre et arrêter la flopée d'erreurs de CSRF".

**Comment by kemenaran** [comment]
C'est activé à 100% des utilisateurs, et ça fonctionne.
