### ISSUE TITLE
Implémenter les retours de l'audit d'accessibilité

### ISSUE THREAD

**Issue by Keirua** [betagouv/demarches-simplifiees.fr#5162]
L'audit d'accessibilité effectué sur 5 pages suggère les modifications suivantes (P01…P05).
Il couvre 25 points

Les quelques points suivants n'incluent **PAS** les modifications sur le dépot de démarche qui contient le plus de boulot.

# P01: [Page d'accueil](https://www.demarches-simplifiees.fr/)

 - [x] ajouter un [alt sur le logo "République française"](https://github.com/betagouv/demarches-simplifiees.fr/pull/4942)

# P02: [Connexion](https://www.demarches-simplifiees.fr/users/sign_in)

 - [ ] Une fois connecté le bouton "Mon compte" qui controle une zone affichée ou masquée n'est pas accessible
 - [x] Dans formulaire de connexion, le contrôle de saisie n'est pas pertinent. ([fait: indication visuelle du format attendu](https://github.com/betagouv/demarches-simplifiees.fr/pull/5218))
 - [x] Le bouton aide n'est pas un vrai bouton -> utilisation au clavier impossible (#5277)
 - [x] Structure HTML incorrecte ([corrigé](https://github.com/betagouv/demarches-simplifiees.fr/pull/5217))

## Bouton "mon compte"

- Utiliser le modèle de conception aria "disclosure" : https://www.w3.org/TR/wai-aria-practices-1.1/#disclosure _(ie: afficher une flèche sur le bouton pour indiquer que c'est un dropdown)_
- Renseigner le alt de l'image avec le même contenu que le title

## Bouton "aide"

- utiliser un vrai bouton et le modèle de conception aria "disclosure". ([corrigé](https://github.com/betagouv/demarches-simplifiees.fr/pull/5277) sans utiliser le modèle aria-disclosure )

## Formulaire de connexion :

- Indiquer le format pour l'email dans le label par exemple (nom@site.com)
- Indiquer le format pour le password dans le label.
- Supprimer l'autofocus (#5487)

## Structure HTML incorrecte

- Absence de titre H1 -> Ajouter un titre H1 par exemple sur le lien "démarche simplifiée"
- Utilisation inapproprié d'un titre pour le passage de texte "Un outil simple" -> Supprimer le titre "Un outil simple"

# P03: [Contact](https://www.demarches-simplifiees.fr/contact?tags=landing)

 - [ ] Le système de mise à jour dynamique des réponses à partir de la liste déroulante des questions pose un problème d'accessibilité : dans le contexte d'une navigation en mode formulaire, le contenu qui apparait sera ignoré par les technologies d'assistance.
 - [x] L'indication visuelle (etoile) pour les champs obligatoires est insuffisante (#5268)

## Mise à jour dynamique des réponses

- [ ] Ajouter un texte caché par positionnement CSS associé au label : "Des suggestions de réponses seront données après le choix de la question";
- [ ] Ajouter un tabindex="0" sur le bloc d'information ajouté.

## Champs obligatoires

- [x] Ajouter un passage de texte avant le formulaire "Les champs précédés d'une étoile sont obligatoires" (#5268)

# P04: [Administration](https://www.demarches-simplifiees.fr/administration)

Conforme

# P05: [Commencer/déposer une démarche](https://www.demarches-simplifiees.fr/commencer/demande-autorisation-pour-les-entreprises-uniper)

## Écran «commencer»

 - [x] Alt logo peu pertinent. [Mettre le service à la place.](https://github.com/betagouv/demarches-simplifiees.fr/pull/5166)
 - [x] Le lien "Aller à l'accueil de demarches-simplifées.fr" n'a pas un intitulé pertinent. Modifier l'intitulé du lien : "Accueil de votre dossier sur demarches-simplifiées.fr" par exemple. ([corrigé](https://github.com/betagouv/demarches-simplifiees.fr/pull/5215))

## 7.1 Compatibilité des composants javascript:

- [ ] "Inviter une personne à modifier ce dossier"
   = Utiliser le modèle de conception ARIA ""disclosure""

### Gestion du focus

- [ ] ""inviter une personne à modifier ce dossier""
   = Ajouter un tabindex=""-1"" sur le titre ""Personnes invitées à modifier ce dossier""
   = A l'issue de l'envoi repositionner le focus sur ce titre

- [ ] Téléchargement de fichier
   = A l'issue du téléchargement, repositionner le focus sur le bouton permettant de supprimer ce téléchargement
- [ ] remplacer un fichier
   = Repositionner le focus sur le bouton de téléchargement qui apparait

### Utilisation de lien et de bouton

- [ ] Remplacer le lien ""supprimer"" associé au téléchargement par un bouton ou utiliser le modèle de conception ARIA ""button"" : https://www.w3.org/TR/wai-aria-practices-1.1/#button

### Indicateur de progression du téléchargement
- [ ] Utiliser le modèle de conception ""progressbar"" (cf note pour le détail)

### Processus de la liste de choix ""transporteur public routier""

 - ce composant (select2) nécessite une étude complémentaire
   - on a remplacé les petits sélecteurs (moins de 5 éléments) par des checkboxes et radio boutons
   - on réfléchit à remplacer ce composant, où suivre les mises à jour d'accessibilité

## 11.6 "Au moins un groupe de champ de même nature n'est pas associé à une légende.

Par exemple :

 - la légende pour Civilité est constitué d'un label ce qui n'est pas approprié
Dans l'écran 2, tous les titres des blocs devraient être des légendes de regroupement

Correction :

 - [ ] Remplacer tous les titres des blocs par des fieldset/legend"

## 11.10 "Dans au moins un formulaire, le contrôle de saisie n'est pas pertinent.

Par exemple :

- Les indications liés à certains champs, par exemple à la case à cocher ""déclaration sur l'honneur"", à la saisie du NIC etc ne sont pas liées aux champs concernés

Correction :

 - [ ] Lier toutes les indications préalables à la saisie avec une propriété aria-describedby

**Comment by Keirua** [comment]
C'est difficile à lire dans le corps de l'issue, et ça nuit à la clarté de la situation et à la possibilité se répartir le travail.

De manière macro, voici le reste à faire :

 - il faut implémenter `aria-disclosure` sur la page contact
 - il faut implémenter `aria-disclosure` sur les menus déroulants (mon compte, inviter…)
 - le champ **pièce justificative** n'est pas accessible (gestion du focus, navigation pour suppression, barre de chargement)
 - les champs **région/commune/département/adresse** utilisent select2 qui n'est pas accessible. Il y a [une issue](https://github.com/betagouv/demarches-simplifiees.fr/issues/4865#issuecomment-641207475) là dessus
 - les champs **sélection multiple** utilise select2 qui n'a pas d'équivalent accessible.
 - peut-on aller plus loin pour le **champ carte** ?
 - corriger les **tests autos d'accessibilité** qui ont des exceptions

Le jour où on a fait tout ça (c'est très jouable)… champagne !

**Comment by krichtof** [comment]
Pb zoom à 200% sur la page contact

**Comment by krichtof** [comment]
Résumé de ce qui est fait et ce qui reste à faire :


- [x] Il faut implémenter `aria-disclosure` sur la page contact 
   https://github.com/betagouv/demarches-simplifiees.fr/pull/5567
- [x] il faut implémenter `aria-disclosure` sur les menus déroulants (mon compte, inviter…) 
   https://github.com/betagouv/demarches-simplifiees.fr/pull/5563)
- [x] le champ **pièce justificative** n'est pas accessible (gestion du focus, navigation pour suppression, barre de chargement)
  https://github.com/betagouv/demarches-simplifiees.fr/pull/5988
  
- [x] les champs **région/commune/département/adresse** utilisent select2 qui n'est pas accessible. 
  https://github.com/betagouv/demarches-simplifiees.fr/pull/5654

- [x] les champs **sélection multiple** utilise select2 qui n'a pas d'équivalent accessible.
  https://github.com/betagouv/demarches-simplifiees.fr/pull/5903
  
- [ ] peut-on aller plus loin pour le **champ carte** ?
- [x] corriger les **tests autos d'accessibilité** qui ont des exceptions
