### ISSUE TITLE
Mettre à jour vers Rails 6.1

### ISSUE THREAD

**Issue by kemenaran** [betagouv/demarches-simplifiees.fr#5886]
Rails 6.1 est sorti en décembre 2020. Il y a plusieurs [nouveautés](https://weblog.rubyonrails.org/2020/12/9/Rails-6-1-0-release/) qui nous intéressent :

- Utilisation de bases de données en read-only (ça nous permettrait de taper la réplique en cas de charge de la base principale)
- Détection et interdiction des requêtes N+1

Le [plan de mise à jour](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-6-0-to-rails-6-1) a l'air assez simple.

### Sous-tâches

- [x] Migrer à Sprockets 4 (#5932)
- [x] Supprimer les gems inutiles et incompatibles avec Rails 6.1 (#5914)
- [x] Corriger les requêtes ActiveRecord incompatibles avec Rails 6.1 (#5920)
- [x] Migrer les hooks du scan anti-virus et du filigrane vers un système compatible avec Rails 6.1 (#5979)
- [x] Utiliser Rails 6.1 (#5955)
- [x] Migrer la configuration vers les réglages par défaut de Rails 6.1 (#6036)
