### ISSUE TITLE
Rendre impossible d'avoir des Admins/Instructeur/Expert sans user

### ISSUE THREAD

**Issue by kemenaran** [betagouv/demarches-simplifiees.fr#6976]
**Décrivez le bug**
Aujourd'hui, en production, on a 3 Administrateurs et 6 Instructeurs sans User associé - ce qui devrait être impossible.

Ça fait planter certains templates (voir https://sentry.io/organizations/demarches-simplifiees/issues/2812624703/)

**Reproduction**
Comment reproduire le problème :

```ruby
> Administrateur.where.missing(:user).count
3
```

**Cause**

C'est parce que le schéma actuel lie les Admins aux Users avec une colonne `users.administrateur_id`. On ne peut donc pas écrire de contrainte qui garantisse qu'un Administrateur a toujours un User.

À la place, on devrait avoir une colonne `administrateur.user_id` – sur laquelle on pourrait mettre une contrainte d'unicité et de non-nullité.

**Questions**

- Est-ce qu'on peut bien supprimer les Administrateurs et Instructeurs en question en prod ?
- Est-ce que ça vaut le coup de faire cette migration de foreign-key, pour éviter de la bad-data dans l'avenir ?
  (Si oui je me sens de le faire.)

## À faire

1. Corriger AdministrateursProcedure :
  - [x] Supprimer les AdministrateursProcedure quand un Administrateur est supprimé (#6992)
  - [x] Ajouter une foreign_key pour qu'un AdministrateursProcedure référence forcément un administrateur valide (#6992)
  - [x]  Supprimer les AdministrateursProcedure quand une Procedure est supprimée (#7013)
  - [x] Ajouter une foreign_key pour qu'un AdministrateursProcedure référence forcément une procédure valide (#7013)
2. Corriger AdministrateursInstructeur (#7001) :
  - [x] Supprimer les AdministrateursInstructeur quand un Instucteur est supprimé
  - [x] Ajouter une foreign_key pour qu'un AdministrateursInstructeur référence forcément un administrateur et un instructeur valide 
3. Créer les foreign keys de User vers les modèles associés (#7019) :
  - [x] Créer trois colonnes : `administrateurs.user_id`, `instructeurs.user_id`, `experts.user_id`
  - [x] Écrire la donnée dedans à chaque `after_save`
  - [x] Ajouter une moulinette qui backporte les anciennes données dans les nouvelles colonnes
4. Basculer les relations de User vers les modèles associés (#7050)
  - [x] Changer le sens de l'association dans les modèles
  - [x] Supprimer le `after_save` qui faisait du double-write
  - [x] Ignorer anciennes les colonnes sur user
5. Rectifier les données en prod (#7070)
  - [x] Supprimer les Administrateurs, Instructeurs et Experts sans User
6. Ajouter des contraintes, et supprimer les anciennes colonnes (#7088)
  - [x] Ajouter une contrainte de foreign key, un COLUMN NOT NULL, un index
  - [x] Supprimer les colonnes `users.administrateur_id`, `users.instructeur_id`, `users.expert_id`

**Comment by kemenaran** [comment]
Ah oui, exact. Miam, plus de bad data ! Merci d'avoir levé ça.

Effectivement on a bien en prod :
- des AdministrateursProcedure dont l'administrateur n'existe plus,
- des AdministrateursInstructeur dont l'instructeur n'existe plus.

Le plan serait donc de :
1. Corriger les tables de jointures, nettoyer la bad-data, rajouter des foreign-key,
2. Puis corriger le modèle User, et pareil blinder de foreign key.

Bon, au moins on aura un modèle de données plus carré ensuite…

**Comment by kemenaran** [comment]
Y'a une pétouille restante sur le double-write (tant que la relation n'a pas changé définitivement de sens, les delete en cascade ne fonctionnent pas trop).

Je creuse ça, et je met à jour la PR ensuite.

**Comment by kemenaran** [comment]
Bon bin ça y est, la relation est inversée, le schéma est blindé, y'a plus d'admins sans users en base, yay !
